=== meenu-gupta/huma-server-sdk/extensions/module_result/modules/schemas/alcohol_schema.json
{
  "$id": "com.medopad.platformplay.alcohol.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "icon": {
      "type": "object",
      "description": "Initially choose an icon from the enumerated list (but not UPLOADED_S3).  Later it could be desirable to upload icon artwork to S3",
      "properties": {
          "iconType": {
            "$ref": "#/definitions/iconType"
          },
          "s3icon": {
            "$ref": "#/definitions/s3Object"
          }
      },
      "required": [
        "iconType"
      ],
      "additionalProperties": false
    },
    "uuid": {
      "type": "string",
      "format": "uuid",
      "examples": [
        "67ed4d53-37e0-4538-bb7a-6ecb62e6cd55"
      ]
    },
    "s3Object": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "region": {
          "type": "string"
        },
        "bucket": {
          "type": "string"
        }
      },
      "required": [
        "key",
        "region",
        "bucket"
      ]
    },
    "section": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/uuid"
        },
        "icon": {
          "$ref": "#/definitions/icon"
        },
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256,
          "examples": [
            "Beer & Cider",
            "Spirits"
          ]
        },
        "strengthOptions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/strengthOption"
          },
          "minLength": 1
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/alcoholItem",
            "minLength": 1
          },
          "additionalProperties": false
        }
      },
      "required": [
        "id",
        "title",
        "strengthOptions",
        "items"
      ]
    },
    "strengthOption": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "value": {
          "type": "number",
          "minimum": 0.005,
          "maximum": 1.0,
          "description": "Alcohol percentage by volume (ABV) to use for this strength option, e.g. 0.04 is 4%.  Range 0.5% - 100%",
          "examples": [
            0.04,
            0.125
          ]
        }
      },
      "required": [
        "label",
        "value"
      ],
      "additionalProperties": false
    },
    "alcoholItem": {
      "type": "object",
      "description": "A row for a particular type of drink, e.g. bottle of beer, large shot",
      "properties": {
        "id": {
          "$ref": "#/definitions/uuid"
        },
        "icon": {
          "$ref": "#/definitions/icon"
        },
        "label": {
          "type": "string",
          "minLength": 1,
          "maxLength": 25
        },
        "plural": {
          "type": "string",
          "description": "Word for apps to use when there are more than one items",
          "examples": ["cans", "bottles"],
          "minLength": 1,
          "maxLength": 25
        },
        "singular": {
          "type": "string",
          "description": "Word for apps to use when there is one item",
          "examples": ["can", "bottle"],
          "minLength": 1,
          "maxLength": 25
        },
        "volume": {
          "type": "number",
          "minimum": 0,
          "description": "How much liquid is in a single one of this item, in litres.",
          "examples": [0.568, 0.25]
        }
      },
      "required": [
        "icon",
        "label",
        "plural",
        "singular",
        "volume"
      ],
      "additionalProperties": false
    },
    "iconType": {
      "enum": [
        "ALCOPOP",
        "BEER_BOTTLE",
        "BEER_CAN",
        "BEER_LITRE",
        "BEER_PINT",
        "CHAMPAGNE",
        "GENERIC",
        "PORT",
        "SHOT",
        "SPARKLING_WINE",
        "SPIRIT",
        "UPLOADED_S3",
        "WINE"
      ]
    }
  },
  "properties": {
    "instruction": {
      "type": "string",
      "description": "Text to go above the list of sections on the main module screen.  Remember to keep this consistent with the period.",
      "minLength": 1,
      "maxLength": 200
    },
    "period": {
      "type": "string",
      "description": "ISO duration for period surveyed",
      "examples": ["P1W", "P1M"],
      "minLength": 3,
      "maxLength": 5
    },
    "questionText": {
      "type": "string",
      "description": "Text for the yes/no question at the start of the module",
      "minLength": 1,
      "maxLength": 100
    },
    "sections": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/section",
        "minLength": 1
      }
    }
  },
  "required": [
    "instruction",
    "questionText",
    "sections"
  ],
  "additionalProperties": false
}

=== meenu-gupta/huma-server-sdk/extensions/module_result/modules/schemas/alcohol_example.json
{
  "questionText": "Do you drink alcohol?",
  "instruction": "Add the types and amounts of alcohol you have consumed in the past week",
  "period": "P1W",
  "sections": [
    {
      "id": "78c10616-e668-46c7-80d5-9a31221f9054",
      "title": "Beer, Lager or Cider",
      "icon": {
        "iconType": "BEER_PINT"
      },
      "strengthOptions": [
        {
          "label": "Light (less than 4%)",
          "value": 0.02
        },
        {
          "label": "Medium (4% to 6%)",
          "value": 0.05
        },
        {
          "label": "Strong (more than 6%)",
          "value": 0.075
        }
      ],
      "items": [
        {
          "id": "17ed4d53-37e0-4538-bb7a-6ecb62e6cd55",
          "icon": {
            "iconType": "BEER_BOTTLE"
          },
          "label": "Bottle",
          "singular": "Bottle",
          "plural": "Bottles",
          "volume": 0.330
        },
        {
          "id": "27ed4d53-37e0-4538-bb7a-6ecb62e6cd55",
          "icon": {
            "iconType": "BEER_CAN"
          },
          "label": "Can",
          "singular": "Can",
          "plural": "Cans",
          "volume": 0.440
        },
        {
          "id": "37ed4d53-37e0-4538-bb7a-6ecb62e6cd55",
          "icon": {
            "iconType": "BEER_PINT"
          },
          "label": "Pint",
          "singular": "Pint",
          "plural": "Pints",
          "volume": 0.568
        },
        {
          "id": "47ed4d53-37e0-4538-bb7a-6ecb62e6cd55",
          "icon": {
            "iconType": "BEER_LITRE"
          },
          "label": "Litre",
          "singular": "Litre",
          "plural": "Litres",
          "volume": 1.0
        }
      ]
    },
    {
      "id": "e6437d16-b709-4361-bae2-72795af5bdd2",
      "title": "Wine or Sparkling Wine",
      "icon": {
        "iconType": "GENERIC"
      },
      "strengthOptions": [
        {
          "label": "Light (less than 12%)",
          "value": 0.11
        },
        {
          "label": "Normal (12% to 13%)",
          "value": 0.125
        },
        {
          "label": "Heavy (more than 13%)",
          "value": 0.14
        }
      ],
      "items": [
        {
          "id": "59a96758-d88c-4939-94af-98c41b3718ba",
          "icon": {
            "iconType": "WINE"
          },
          "label": "Small glass",
          "singular": "Small glass",
          "plural": "Small glasses",
          "volume": 0.125
        },
        {
          "id": "f95828fc-ce86-493c-a340-184967b888c3",
          "icon": {
            "iconType": "WINE"
          },
          "label": "Standard glass",
          "singular": "Standard glass",
          "plural": "Standard glasses",
          "volume": 0.175
        },
        {
          "id": "284f5608-2081-4c30-84ea-138142485956",
          "icon": {
            "iconType": "WINE"
          },
          "label": "Large glass",
          "singular": "Large glass",
          "plural": "Large glasses",
          "volume": 0.25
        },
        {
          "id": "17178c1d-12d9-49fe-bc8f-b7dbf01b6734",
          "icon": {
            "iconType": "GENERIC"
          },
          "label": "Bottle",
          "singular": "Bottle",
          "plural": "Bottles",
          "volume": 0.75
        }
      ]
    },
    {
      "id": "97ed4d53-37e0-4538-bb7a-6ecb62e6cd55",
      "title": "Shots",
      "icon": {
        "iconType": "SHOT"
      },
      "strengthOptions": [
        {
          "label": "Standard",
          "value": 0.4
        }
      ],
      "items": [
        {
          "id": "345d4d53-37e0-4538-bb7a-6ecb62e6cd55",
          "icon": {
            "iconType": "SHOT"
          },
          "label": "Small shot",
          "singular": "Small shot",
          "plural": "Small shots",
          "volume": 0.025
        },
        {
          "id": "11ed4d53-37e0-4538-bb7a-6ecb62e6cd55",
          "icon": {
            "iconType": "SHOT"
          },
          "label": "Large shot",
          "singular": "Large shot",
          "plural": "Large shots",
          "volume": 0.035
        }
      ]
    },
    {
      "id": "21253ae8-7a2f-41fb-8bd6-d101d1c0b1fa",
      "title": "Alcopops",
      "icon": {
        "iconType": "ALCOPOP"
      },
      "strengthOptions": [
        {
          "label": "Normal",
          "value": 0.05
        }
      ],
      "items": [
        {
          "id": "8da598ba-e8da-4415-b700-b9acf8099871",
          "icon": {
            "iconType": "ALCOPOP"
          },
          "label": "Bottle",
          "singular": "Bottle",
          "plural": "Bottles",
          "volume": 0.275
        }
      ]
    },
    {
      "id": "58574e22-59f0-406c-a2c3-f92966b9d30f",
      "title": "Fortified Wine",
      "icon": {
        "iconType": "PORT"
      },
      "strengthOptions": [
        {
          "label": "Standard",
          "value": 0.19
        }
      ],
      "items": [
        {
          "id": "bb40354f-45fe-40b0-81b6-64ceb1d4acbc",
          "icon": {
            "iconType": "PORT"
          },
          "label": "Glass",
          "singular": "Glass",
          "plural": "Glasses",
          "volume": 0.05
        }
      ]
    },
    {
      "id": "3ad7b042-8bf3-4b39-97f3-de8f6f2fded0",
      "title": "Spirits",
      "icon": {
        "iconType": "SPIRIT"
      },
      "strengthOptions": [
        {
          "label": "Standard",
          "value": 0.4
        }
      ],
      "items": [
        {
          "id": "c61f8be1-29f0-4761-a3f4-bececd447304",
          "icon": {
            "iconType": "SPIRIT"
          },
          "label": "Single",
          "singular": "Single",
          "plural": "Singles",
          "volume": 0.025
        },
        {
          "id": "3600ee9e-e9a2-4422-a875-10958cd584be",
          "icon": {
            "iconType": "SPIRIT"
          },
          "label": "Large single",
          "singular": "Large single",
          "plural": "Large singles",
          "volume": 0.035
        },
        {
          "id": "0a1e02be-9b72-4105-994c-4d8378d60f30",
          "icon": {
            "iconType": "SPIRIT"
          },
          "label": "Double",
          "singular": "Double",
          "plural": "Doubles",
          "volume": 0.05
        },
        {
          "id": "cabad487-3b0e-4fcb-87d0-70e03d924d18",
          "icon": {
            "iconType": "SPIRIT"
          },
          "label": "Large double",
          "singular": "Large double",
          "plural": "Large doubles",
          "volume": 0.07
        }
      ]
    }
  ]
}
