=== meenu-gupta/huma-server-sdk/extensions/module_result/modules/schemas/questionnaire_schema.json
{
  "$id": "com.medopad.platformplay.questionnaire.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "uuid": {
      "type": "string",
      "format": "uuid",
      "examples": ["67ed4d53-37e0-4538-bb7a-6ecb62e6cd55"]
    },
    "datetime": {
      "type": "string",
      "format": "date-time",
      "examples": ["2008-09-15T15:53:00+05:00"]
    },
    "s3Object": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "region": {
          "type": "string"
        },
        "bucket": {
          "type": "string"
        }
      },
      "required": ["key", "region", "bucket"]
    },
    "condition": {
      "type": "object",
      "properties": {
        "questionId": {
          "$ref": "#/definitions/uuid"
        },
        "eq": {
          "type": ["string", "number"]
        },
        "neq": {
          "type": ["string", "number"]
        }
      }
    },
    "rule": {
      "type": "object",
      "properties": {
        "allOf": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        },
        "anyOf": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        },
        "jumpToId": {
          "$ref": "#/definitions/uuid"
        }
      },
      "required": ["jumpToId"]
    },
    "logic": {
      "type": "object",
      "properties": {
        "rules": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/rule"
          }
        },
        "reuse": {
          "$ref": "#/definitions/reuse"
        },
        "isEnabled": {
          "type": "boolean"
        }
      },
      "required": ["rules", "isEnabled"]
    },
    "reuse": {
      "type": "object",
      "properties": {
        "questionId": {
          "$ref": "#/definitions/uuid"
        },
        "loop": {
          "type": "object",
          "properties": {
            "isEnabled": {
              "type": "boolean"
            },
            "choices": {
              "enum": ["selected", "unselected", "all"]
            }
          }
        },
        "recall": {
          "type": "object",
          "properties": {
            "isEnabled": {
              "type": "boolean"
            }
          },
          "required": ["isEnabled"]
        }
      }
    },
    "pageType": {
      "enum": ["INFO", "QUESTION", "SUBMISSION"]
    },
    "page": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/uuid"
        },
        "order": {
          "type": "number"
        },
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },
        "description": {
          "type": "string",
          "minLength": 0,
          "maxLength": 1024
        }
      },
      "required": ["type", "order"]
    },
    "infoPage": {
      "allOf": [
        {
          "$ref": "#/definitions/page"
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "const": "INFO"
            },
            "image": {
              "$ref": "#/definitions/s3Object"
            }
          },
          "required": ["type"]
        }
      ]
    },
    "submissionPage": {
      "allOf": [
        {
          "$ref": "#/definitions/page"
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "const": "SUBMISSION"
            },
            "buttonText": {
              "type": "string",
              "minLength": 1,
              "maxLength": 70
            }
          },
          "required": ["type"]
        }
      ]
    },
    "questionPage": {
      "allOf": [
        {
          "$ref": "#/definitions/page"
        },
        {
          "type": "object",
          "properties": {
            "type": {
              "const": "QUESTION"
            },
            "items": {
              "type": "array",
              "items": {
                "anyOf": [
                  {
                    "$ref": "#/definitions/infoItem"
                  },
                  {
                    "$ref": "#/definitions/textQuestionItem"
                  },
                  {
                    "$ref": "#/definitions/textChoiceQuestionItem"
                  },
                  {
                    "$ref": "#/definitions/scaleQuestionItem"
                  },
                  {
                    "$ref": "#/definitions/booleanQuestionItem"
                  },
                  {
                    "$ref": "#/definitions/dateQuestionItem"
                  },
                  {
                    "$ref": "#/definitions/numberQuestionItem"
                  },
                  {
                    "$ref": "#/definitions/durationSecondsQuestionItem"
                  },
                  {
                    "$ref": "#/definitions/autocompleteQuestionItem"
                  },
                  {
                    "$ref": "#/definitions/mediaQuestionItem"
                  }
                ]
              }
            }
          },
          "required": ["items"]
        }
      ]
    },
    "pageItemFormat": {
      "enum": [
        "TEXT",
        "TEXTCHOICE",
        "SCALE",
        "BOOLEAN",
        "DATE",
        "NUMERIC",
        "DURATION",
        "DURATION_SECONDS",
        "COMPOSITE",
        "MEDIA",
        "AUTOCOMPLETE_TEXT"
      ]
    },
    "pageItemSelectionCriteria": {
      "enum": ["SINGLE", "MULTIPLE"]
    },
    "stringOption": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "weight": {
          "type": "integer"
        }
      },
      "required": ["label", "value"]
    },
    "stringOrIntegerOption": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "value": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "integer"
            }
          ]
        },
        "weight": {
          "type": "integer"
        }
      },
      "required": [
        "label",
        "value"
      ]
    },
    "validation": {
      "type": "object",
      "properties": {
        "expression": {
          "type": "string"
        },
        "errorMessage": {
          "type": "string"
        },
        "required": {
          "type": "boolean"
        }
      }
    },
    "field": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/uuid"
        },
        "format": {
          "enum": [
            "TEXT_CHOICE",
            "NUMERIC"
          ]
        },
        "required": {
          "type": "boolean"
        },
        "validation": {
          "$ref": "#/definitions/validation"
        }
      }
    },
    "pageItem": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/uuid"
        },
        "format": {
          "$ref": "#/definitions/pageItemFormat"
        },
        "order": {
          "type": "number"
        },
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },
        "description": {
          "type": "string",
          "minLength": 0,
          "maxLength": 1024
        },
        "fields": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/field"
          }
        }
      },
      "required": ["order", "text", "format"]
    },
    "autocompletePageItem": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/uuid"
        },
        "format": {
          "const": "AUTOCOMPLETE_TEXT"
        },
        "order": {
          "type": "number"
        },
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 256
        },
        "description": {
          "type": "string",
          "minLength": 0,
          "maxLength": 1024
        },
        "required": {
          "type": "boolean"
        },
        "logic": {
          "$ref": "#/definitions/logic"
        },
        "multipleAnswers": {
          "$ref": "#/definitions/multipleAnswersType"
        }
      },
      "required": ["order", "text", "format", "required"]
    },
    "infoItem": {
      "allOf": [
        {
          "$ref": "#/definitions/pageItem"
        },
        {
          "type": "object",
          "properties": {
            "image": {
              "$ref": "#/definitions/s3Object"
            }
          }
        }
      ]
    },
    "questionItem": {
      "allOf": [
        {
          "$ref": "#/definitions/pageItem"
        },
        {
          "type": "object",
          "properties": {
            "required": {
              "type": "boolean"
            },
            "logic": {
              "$ref": "#/definitions/logic"
            }
          },
          "required": ["required"]
        }
      ]
    },
    "textQuestionItem": {
      "allOf": [
        {
          "$ref": "#/definitions/questionItem"
        },
        {
          "type": "object",
          "properties": {
            "regex": {
              "type": "string",
              "minLength": 1,
              "maxLength": 1024
            },
            "defaultValue": {
              "type": "string"
            },
            "placeholder": {
              "type": "string",
              "minLength": 1,
              "maxLength": 1024
            }
          }
        }
      ]
    },
    "textChoiceQuestionItem": {
      "allOf": [
        {
          "$ref": "#/definitions/questionItem"
        },
        {
          "type": "object",
          "properties": {
            "options": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/stringOption"
              }
            },
            "selectionCriteria": {
              "$ref": "#/definitions/pageItemSelectionCriteria"
            },
            "defaultOptions": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": ["options", "selectionCriteria"]
        }
      ]
    },
    "scaleQuestionItem": {
      "allOf": [
        {
          "$ref": "#/definitions/questionItem"
        },
        {
          "type": "object",
          "properties": {
            "options": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/stringOrIntegerOption"
              }
            },
            "lowerBound": {
              "type": "integer"
            },
            "upperBound": {
              "type": "integer"
            },
            "defaultValue": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "isVisualAnalogueScale": {
              "type": "boolean"
            }
          }
        }
      ]
    },
    "booleanQuestionItem": {
      "allOf": [
        {
          "$ref": "#/definitions/questionItem"
        },
        {
          "type": "object",
          "properties": {
            "defaultValue": {
              "type": "boolean"
            }
          }
        }
      ]
    },
    "dateQuestionItem": {
      "allOf": [
        {
          "$ref": "#/definitions/questionItem"
        },
        {
          "type": "object",
          "properties": {
            "includeTime": {
              "type": "boolean"
            }
          }
        }
      ]
    },
    "numberQuestionItem": {
      "allOf": [
        {
          "$ref": "#/definitions/questionItem"
        },
        {
          "type": "object",
          "properties": {
            "unit": {
              "type": "string"
            },
            "lowerBound": {
              "type": "integer"
            },
            "upperBound": {
              "type": "integer"
            },
            "normalRange": {
              "type": "object",
              "properties": {
                "lowerBound": {
                  "type": "integer"
                },
                "upperBound": {
                  "type": "integer"
                },
                "warningMessage" : {
                  "type": "string"
                }
              }
            },
            "allowsIntegersOnly": {
              "type": "boolean"
            },
            "skipByWeight": {
              "type": "integer"
            }
          }
        }
      ]
    },
    "mediaQuestionItem": {
      "allOf": [
        {
          "$ref": "#/definitions/questionItem"
        },
        {
          "type": "object",
          "properties": {
            "mediaType": {
              "type": "array",
              "items": [
                {
                  "$ref": "#/definitions/questionnaireAnswerMediaType"
                }
              ]
            },
            "multipleAnswers": {
              "$ref": "#/definitions/multipleAnswersType"
            }
          },
          "required": ["mediaType"]
        },
        {
          "type": "object",
          "properties": {
            "format": {
              "const": "MEDIA"
            }
          }
        }
      ]
    },
    "multipleAnswersType": {
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "maxAnswers": {
          "type": "number"
        }
      },
      "required": ["enabled"]
    },
    "questionnaireAnswerMediaType": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/questionnaireAnswerMediaItemType"
      }
    },
    "questionnaireAnswerMediaItemType": {
      "type": "string",
      "enum" : ["FILE", "PHOTO", "VIDEO"]
    },
    "durationSecondsQuestionItem": {
      "allOf": [
        {
          "$ref": "#/definitions/questionItem"
        },
        {
          "type": "object",
          "properties": {
            "increment": {
              "type": "integer",
              "minimum": 1
            },
            "lowerBound": {
              "type": "integer"
            },
            "upperBound": {
              "type": "integer"
            }
          }
        }
      ]
    },
    "autocompleteQuestionItem": {
      "allOf": [
        {
          "$ref": "#/definitions/autocompletePageItem"
        },
        {
          "type": "object",
          "properties": {
            "autocomplete": {
              "type": "object",
              "properties": {
                "placeholder": {
                  "type": "string"
                },
                "listEndpointId": {
                  "type": "string"
                },
                "allowFreeText": {
                  "type": "boolean"
                }
              },
              "required": ["listEndpointId"]
            }
          },
          "required": ["autocomplete"]
        }
      ]
    }
  },
  "properties": {
    "pages": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "#/definitions/infoPage"
          },
          {
            "$ref": "#/definitions/questionPage"
          }
        ]
      }
    },
    "region": {
      "enum": ["Denmark", "Germany", "Japan", "Netherlands", "Spain", "Thailand", "UK", "US", "Zimbabwe"]
    },
    "isForManager": {
      "type": "boolean"
    },
    "isHorizonalFlow": {
      "type": "boolean"
    },
    "trademarkText": {
      "type": "string"
    },
    "publisherName": {
      "type": "string"
    },
    "submissionPage": {
      "type": "object",
      "$ref": "#/definitions/submissionPage"
    },
    "isPAM": {
      "type": "boolean"
    },
    "isOnboarding": {
      "type": "boolean"
    },
    "questionnaireType": {
      "enum": ["EQ5D_5L", "PAM", "PROMIS_PAIN", "PROMIS_PHYSICAL", "PROMIS_PHYSICAL_DE", "PROMIS_PAIN_DE", "OBSERVATION_NOTES", "PROMIS_PHYSICAL_ES", "PROMIS_PAIN_ES"]
    }
  },
  "required": ["isForManager", "pages"]
}

=== meenu-gupta/huma-server-sdk/extensions/module_result/modules/schemas/questionnaire_example.json
{
  "isForManager": false,
  "publisherName": "Bruce Willis",
  "questionnaireType": "EQ5D_5L",
  "pages": [
    {
      "type": "INFO",
      "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1667",
      "order": 1,
      "text": "Some hint?",
      "description": "Explain more here?",
      "image": {
        "key": "info.png",
        "region": "us-west-2",
        "bucket": "bucket"
      }
    },
    {
      "type": "QUESTION",
      "items": [
        {
          "logic": {
            "isEnabled": false
          },
          "description": "",
          "id": "composite_question_id",
          "required": true,
          "format": "COMPOSITE",
          "order": 1,
          "text": "What is your waist and hip circumference?",
          "fields": [
            {
              "id": "waist_circumference",
              "format": "NUMERIC",
              "placeholder": "Enter waist circumference",
              "required": true,
              "validation": {
                "expression": "/^\\d{0,3}(?:\\.\\d)?$",
                "errorMessage": "Value cannot include more than one decimal",
                "required": false
              }
            },
            {
              "id": "hip_circumference",
              "format": "NUMERIC",
              "placeholder": "Enter hip circumference",
              "required": true,
              "validation": {
                "expression": "/^\\d{0,3}(?:\\.\\d)?$/gm",
                "errorMessage": "Value cannot include more than one decimal",
                "required": false
              }
            }
          ]
        }
      ],
      "order": 1
    },
    {
      "type": "QUESTION",
      "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
      "order": 1,
      "text": "Some hint?",
      "description": "Explain more here?",
      "items": [
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "TEXT",
          "required": true,
          "order": 1,
          "text": "Text Question",
          "description": "Text Question Description?",
          "regex": "[0-9]{8}",
          "defaultValue": "some text",
          "placeholder": "enter your phone here"
        },
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "TEXTCHOICE",
          "required": true,
          "order": 2,
          "text": "Text Choice Question",
          "description": "Text Choice Question Description?",
          "options": [
            {
              "label": "key1",
              "value": "value1"
            },
            {
              "label": "key2",
              "value": "value2"
            }
          ],
          "selectionCriteria": "SINGLE",
          "defaultOptions": [
            "key1"
          ],
          "logic": {
            "rules": [
              {
                "allOf": [
                  {
                    "questionId": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
                    "neq": 3
                  },
                  {
                    "neq": 4
                  }
                ],
                "jumpToId": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669"
              },
              {
                "anyOf": [
                  {
                    "eq": 8
                  },
                  {
                    "eq": 5
                  }
                ],
                "jumpToId": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1666"
              }
            ],
            "enabled": true
          }
        },
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "SCALE",
          "required": false,
          "order": 3,
          "text": "Scale Question",
          "description": "Scale Question Description?",
          "lowerBound": 1,
          "upperBound": 5,
          "defaultValue": 2
        },
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "BOOLEAN",
          "required": false,
          "order": 4,
          "text": "Boolean Question",
          "description": "Boolean Question Description",
          "defaultValue": true
        },
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "DATE",
          "required": false,
          "order": 5,
          "text": "Date Question",
          "description": "Date Question Description",
          "includeTime": true
        },
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "NUMERIC",
          "required": false,
          "order": 5,
          "text": "Numberic Question",
          "description": "Numberic Question Description",
          "upperBound": 120,
          "lowerBound": 12,
          "unit": "years",
          "normalRange": {
            "lowerBound": 3,
            "upperBound": 6,
            "warningMessage": "string"
          }
        },
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb166a",
          "format": "MEDIA",
          "order": 6,
          "text": "Media Question",
          "description": "Media Question Description",
          "mediaType": ["FILE"],
          "multipleAnswers": {
            "enabled": true,
            "maxAnswers": 20
          }
        },
        {
          "description": "",
          "format": "AUTOCOMPLETE_TEXT",
          "autocomplete": {
            "placeholder": "Search conditions",
            "options": [
              {
                "key": "Ukraine",
                "value": "Ukraine"
              },
              {
                "key": "United Kingdom",
                "value": "United Kingdom"
              }
            ]
          },
          "id": "7c50c7d5-6f4e-4c0b-aeaf-c266eafd056e",
          "logic": {
            "isEnabled": false
          },
          "multipleAnswers": {
            "enabled": true,
            "maxAnswers": 20
          },
          "order": 7,
          "required": true,
          "placeholder": "Enter condition",
          "text": "What condition do you have?"
        },
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "TEXT",
          "required": true,
          "order": 8,
          "description": "Text Question Description?",
          "text": "text value with @{} selected",
          "defaultValue": "some text",
          "placeholder": "enter your phone here",
          "logic": {
            "rules": [],
            "order": 8,
            "reuse": {
              "questionId": "7c50c7d5-6f4e-4c0b-ae2c-c266eafd4621",
              "loop": {
                "isEnabled": true,
                "choices": "selected"
              },
              "recall": {
                "isEnabled": true
              }
            },
            "isEnabled": true
          }
        },
        {
          "description": "",
          "format": "AUTOCOMPLETE_TEXT",
          "autocomplete": {
            "placeholder": "Search conditions",
            "options": [
              {
                "key": "Ukraine",
                "value": "Ukraine"
              },
              {
                "key": "United Kingdom",
                "value": "United Kingdom"
              }
            ]
          },
          "id": "7c50c7d5-6f4e-5f0b-aeaf-c277eafd056e",
          "logic": {
            "rules": [],
            "order": 8,
            "reuse": {
              "questionId": "7c50c7d5-6f4e-4c0b-ae2c-c266eafd4621",
              "loop": {
                "isEnabled": true,
                "choices": "unselected"
              },
              "recall": {
                "isEnabled": true
              }
            },
            "isEnabled": true
          },
          "multipleAnswers": {
            "enabled": true,
            "maxAnswers": 20
          },
          "order": 9,
          "required": true,
          "placeholder": "Enter condition",
          "text": "What condition do you have regarding you have not selected @{}?"
        }
      ]
    },
    {
      "type": "QUESTION",
      "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1666",
      "order": 2,
      "text": "Some hint?",
      "description": "Explain more here?",
      "items": [
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "TEXT",
          "required": true,
          "order": 1,
          "text": "Text Question",
          "description": "Text Question Description?",
          "regex": "[0-9]{8}",
          "defaultValue": "some text",
          "placeholder": "enter your phone here"
        },
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "TEXTCHOICE",
          "required": true,
          "order": 2,
          "text": "Text Choice Question",
          "description": "Text Choice Question Description?",
          "options": [
            {
              "label": "key1",
              "value": "value1"
            },
            {
              "label": "key2",
              "value": "value2"
            }
          ],
          "selectionCriteria": "MULTIPLE",
          "defaultOptions": [
            "key1",
            "key2"
          ]
        },
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "SCALE",
          "required": false,
          "order": 3,
          "text": "Scale Question",
          "description": "Scale Question Description?",
          "options": [
            {
              "label": "key1",
              "value": "value1"
            },
            {
              "label": "key2",
              "value": "value2"
            }
          ],
          "defaultValue": "value1"
        },
        {
          "id": "d23deeb0-a72e-4ab0-bba0-e52bc6fb1669",
          "format": "DATE",
          "required": false,
          "order": 4,
          "text": "Date Question",
          "description": "Date Question Description",
          "includeTime": false
        }
      ]
    }
  ]
}
